services:
  - type: web
    name: aetherdesk
    runtime: python
    plan: starter
    region: frankfurt
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    preDeployCommand: python manage.py migrate --noinput
    startCommand: gunicorn aetherdesk.wsgi:application --workers 2 --threads 4 --timeout 60
    healthCheckPath: /healthz/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: USE_CLOUDFLARE_R2
        value: "False"
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_CUSTOM_DOMAIN
        sync: false
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.postmarkapp.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_USE_TLS
        value: "True"
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: SENTRY_DSN
        sync: false
